os: linux
dist: focal
language: erlang
jobs:
  include:
    - otp_release: 23.0
    - otp_release: 22.3
    - otp_release: 21.3
      dist: xenial
script:
  - rebar3 compile
  - rebar3 as dev lint
  - rebar3 edoc
  - rebar3 eunit -c
  - rebar3 ct -c
  - rebar3 cover -v --min_coverage 80
  - rebar3 dialyzer
